### ISSUE TITLE
Any chance this will get updated to use the new v2 API?

### ISSUE THREAD

**Issue by dtate888** [YiddishNinja/TaxRates-node#1]

**Comment by YiddishNinja** [comment]
There's no V2 API for this. This is the TaxRates API, which was a simplified and rate-limited subset of Avalara's full functionality. They seem to have killed it, requiring everyone to use the full AvaTax API. This will not be updated to become a full AvaTax client library.

**Comment by dtate888** [comment]
Thanks for the clarification. I think I will just hack something together using Node.js request module or something, though if I had more time to mess around with this, it would be fun to take a hack a new revision of your wrapper. (Would be my first real commit to anything open-source... :P )
Thanks again,
